version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:34"
  target-branch: main
  labels:
    - CI/CD
    - skip-changelog
  groups:
    actions:
      applies-to: "version-updates"
      patterns: ["*"]
    actions-security:
      applies-to: "security-updates"
      patterns: ["*"]

- package-ecosystem: pip
  directories:
    - "/"
    - "/docker"
    - "/.github/utils"
  schedule:
    interval: weekly
    time: "03:06"
  target-branch: main
  labels:
    - CI/CD
    - skip-changelog
  groups:
    python:
      applies-to: "version-updates"
      patterns: ["*"]
    python-security:
      applies-to: "security-updates"
      patterns: ["*"]
