name: Tests

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  VENV_NAME: .ci-venv

# Only run a single complete workflow for a single branch at a time.
# Cancel in-progress runs of the same workflow for the same branch.
# This is useful for pull requests, where the branch may be updated multiple times
# and we want to avoid running multiple workflows for the same branch.
concurrency:
  group: 'ci-tests-${{ github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pytest:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Randomizer
        id: randomizer
        run: |
          # Create a unique name for the virtual environment
          random_part="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 | tr '[:upper:]' '[:lower:]')"

          if [ -z "${random_part}" ]; then
            echo "Error: Failed to generate random part for virtual environment name and docker names"
            exit 1
          fi

          echo "random_part=${random_part}" >> $GITHUB_OUTPUT

      - name: Setup virtual environment
        id: venv
        run: |
          venv_name="${{ env.VENV_NAME }}-${{ steps.randomizer.outputs.random_part }}"

          if [ -d ${venv_name} ]; then
            echo "Virtual environment (folder: "${venv_name}") already exists"
            exit 1
          fi
          python -m venv ${venv_name}

          echo "venv_name=${venv_name}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          source ${{ steps.venv.outputs.venv_name }}/bin/activate
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -U -e .[testing]
          deactivate

      - name: Run tests
        run: ${{ steps.venv.outputs.venv_name }}/bin/pytest -vv --color=yes --cov-report=

      - name: Remove virtual environment
        if: always()
        run: rm -rf ${{ steps.venv.outputs.venv_name }}
